gateway/compose.local.yaml
gateway/compose.production.yaml
gateway/compose/local/django/start
gateway/compose/production/django/start
gateway/pyproject.toml
gateway/requirements/base.txt
gateway/sds_gateway/api_methods/helpers/index_handling.py
gateway/sds_gateway/api_methods/helpers/reconstruct_file_tree.py
gateway/sds_gateway/api_methods/helpers/rh_schema_generator.py
gateway/sds_gateway/api_methods/management/__init__.py
gateway/sds_gateway/api_methods/management/commands/__init__.py
gateway/sds_gateway/api_methods/management/commands/init_indices.py
gateway/sds_gateway/api_methods/serializers/capture_serializers.py
gateway/sds_gateway/api_methods/serializers/file_serializers.py
gateway/sds_gateway/api_methods/tests/test_capture_endpoints.py
gateway/sds_gateway/api_methods/tests/test_file_endpoints.py
gateway/sds_gateway/api_methods/views/capture_endpoints.py
gateway/uv.lock

- Added rh_schema_generator.py
- Added dependencies for ^
- Added function to find rh properties file (rh.json)
- Moved property indexing handling into a separate function on the CaptureViewSet, calling that from the create method
- Instead of checking/creating indices on method call, added management command to run on start
- Added/edited tests

Integrate RH capture properties and optimize create method

---

gateway/README.md
gateway/config/settings/base.py
gateway/config/settings/local.py
gateway/pyproject.toml
gateway/requirements/base.txt
gateway/sds_gateway/templates/500.html
gateway/uv.lock

Found and fixed a few template issues.

Templating fix and validation procedure documented

---

.pre-commit-config.yaml
sdk/docs/changelog.md
sdk/docs/release-checklist.md
sdk/pyproject.toml
sdk/uv.lock

Version 0.1.6 with support for Python 3.10 and 3.11.

SDK Release v0.1.6

---

gateway/compose/production/opensearch/config/roles.yml

Revert "Opensearch roles setup fix"

---

gateway/compose.local.yaml
gateway/compose/local/opensearch/Dockerfile
gateway/sds_gateway/static/css/custom.css
gateway/sds_gateway/static/sass/_layout.scss
gateway/sds_gateway/templates/base.html

CSS changes to the navbar/header, added a local OpenSearch Dockerfile because using the production Docker on local deploy causes errors on OpenSearch.

Site Header CSS Changes, Local Docker updates

---

sdk/docs/changelog.md
sdk/src/spectrumx/api/captures.py
sdk/src/spectrumx/client.py
sdk/src/spectrumx/errors.py
sdk/tests/conftest.py
sdk/tests/e2e_examples/check_build_acceptance.py
sdk/tests/integration/test_captures.py
sdk/tests/ops/test_files.py
sdk/uv.lock

[SFDS 176](https://crc-dev.atlassian.net/browse/SFDS-176)
Capture upload method that combines the file upload with capture creation; with local and integration tests.

New `upload_capture` method for SDK

---

gateway/sds_gateway/static/sass/_components.scss
gateway/sds_gateway/static/sass/_layout.scss
gateway/sds_gateway/templates/base.html
gateway/sds_gateway/templates/users/file_list.html
gateway/sds_gateway/users/urls.py
gateway/sds_gateway/users/views.py
sdk/.gitignore

SDS-UI-Updates fixes for the following:
1) Removed the table border and the line between the table and pagination buttons
2) Added line between the table header row and the first row in the table
3) Fixed the whole page is shifted up under the header. The search input is hiding half way up there
4) the click to change sort should be on the entire header cell, not just the arrows 
5) Fixed "missing sorting arrows"

Gateway UI: files and captures listing

---

gateway/sds_gateway/users/views.py

- Removed code duplicating functionality
- Fixed issue: empty captures or files causes internal error. For context, performing `.split(",")` on an empty string returns an array with a single empty string element (`[""]`)

fixing bug not able to create dataset with no files/captures

---

gateway/sds_gateway/api_methods/helpers/reconstruct_file_tree.py

- Created a function to check file name for metadata file naming convention (more standardized for DRF)
- Run fget from Minio if the file is a metadata file, else create an empty file with the file name from the database
- Not tested locally

Fix for creating large captures timeout

---

gateway/sds_gateway/api_methods/management/commands/init_indices.py
gateway/sds_gateway/api_methods/management/commands/replace_index.py

[SFDS 194](https://crc-dev.atlassian.net/browse/SFDS-194)
Making sure indices are writable before initializing gateway.

`init_indices` also makes indices writable

---

gateway/makefile
gateway/sds_gateway/api_methods/utils/swagger_example_schema.py
gateway/sds_gateway/context_processors.py
gateway/sds_gateway/users/admin.py
gateway/sds_gateway/users/management/commands/list_tests.py
gateway/sds_gateway/users/tests/factories.py
gateway/sds_gateway/users/tests/test_admin.py
gateway/sds_gateway/users/tests/test_drf_urls.py
gateway/sds_gateway/users/tests/test_drf_views.py
gateway/sds_gateway/users/tests/test_swagger.py
gateway/sds_gateway/users/tests/test_views.py
gateway/sds_gateway/users/views.py

The `python manage.py test` command doesn't run some of the tests.
`make test` now defaults to `pytest`, which discovers ~30 additional tests.

Using pytest

---

.pre-commit-config.yaml
sdk/docs/changelog.md
sdk/pyproject.toml
sdk/uv.lock

The usual SDK release checklist.

SDK release v0.1.10

---

gateway/sds_gateway/static/js/captureGroupingComponents.js
gateway/sds_gateway/templates/users/partials/file_browser.html

Add responsiveness when selecting/deselecting all files, confirming/closing modal resets search.

Add select all checkbox and remove all button

---

gateway/sds_gateway/static/js/file-list.js
gateway/sds_gateway/templates/users/file_list.html

[SFDS-34](https://crc-dev.atlassian.net/jira/software/c/projects/SFDS/boards/81?selectedIssue=SFDS-34)
1. Filter expand and collapse functionality
2. Range slider default
3. filter logic update

File list filter tweaks

---

gateway/compose/production/nginx/nginx-default.conf

Fixed images not displaying correctly

---

gateway/sds_gateway/static/css/file-list.css
gateway/sds_gateway/static/js/file-list.js
gateway/sds_gateway/templates/users/file_list.html
gateway/sds_gateway/users/views.py

[SFDS-209](https://crc-dev.atlassian.net/browse/SFDS-209)
1. I don’t think we need the note “Click column headers to sort”
2. Reduce size of the word “Filters”. The various font sizes in the Filters panel seem to be larger than and inconsistent with fonts elsewhere on the page. So, in general, perhaps an audit of fonts (sizes, colors, styles, etc.) for consistency.
3. Increase the number of results displaying within the table before moving to a new page (let’s check what is standard for our other projects with this view). The table frame came be taller. We can also add a dropdown for users to choose number of results displayed (25, 50, 100? I don’t know how many results will be common.
4. “End Date” label sits too close to the date box above it from the start date input. Increase slightly …

ticket 209 and modal

---

gateway/sds_gateway/api_methods/serializers/capture_serializers.py
gateway/sds_gateway/static/js/components.js
gateway/sds_gateway/static/js/file-list.js
gateway/sds_gateway/static/sass/_components.scss
gateway/sds_gateway/static/sass/_layout.scss
gateway/sds_gateway/static/sass/_spectrumx_theme.scss
gateway/sds_gateway/static/sass/project.scss
gateway/sds_gateway/templates/base.html
gateway/sds_gateway/templates/pages/about.html
gateway/sds_gateway/templates/pages/home.html
gateway/sds_gateway/templates/users/dataset_list.html
gateway/sds_gateway/templates/users/partials/captures_page_table.html

- New about and home page
- Removed css file causing conflict 
- Removed duplicate js code
- timestamp format
- header update

header css

---

gateway/sds_gateway/api_methods/tasks.py
gateway/sds_gateway/api_methods/tests/test_celery_tasks.py
gateway/sds_gateway/templates/emails/dataset_download_error.html
gateway/sds_gateway/templates/emails/dataset_download_error.txt
gateway/sds_gateway/templates/users/temporary_zip_download.html
gateway/sds_gateway/users/tasks.py
gateway/sds_gateway/users/tests/test_error_emails.py
gateway/sds_gateway/users/views.py

Add error email template and task. Refactor to break out some long, multi-step functions. Create/update tests for error emails.

Dataset Download: add error email

---

gateway/config/settings/base.py
gateway/sds_gateway/api_methods/admin.py
gateway/sds_gateway/api_methods/tasks.py
gateway/sds_gateway/static/css/alerts.css
gateway/sds_gateway/static/css/bootstrap_overrides.css
gateway/sds_gateway/static/css/components.css
gateway/sds_gateway/static/css/custom.css
gateway/sds_gateway/static/css/project.css
gateway/sds_gateway/static/css/spectrumx_theme.css
gateway/sds_gateway/static/css/variables.css
gateway/sds_gateway/static/js/dataset-list.js
gateway/sds_gateway/static/js/project.js
gateway/sds_gateway/static/js/userSearchComponent.js
gateway/sds_gateway/templates/base.html
gateway/sds_gateway/templates/emails/dataset_download_error.html
gateway/sds_gateway/templates/emails/dataset_download_ready.html
gateway/sds_gateway/templates/emails/email_styles.html
gateway/sds_gateway/templates/emails/share_notification.html
gateway/sds_gateway/templates/pages/home.html
gateway/sds_gateway/templates/users/dataset_list.html
gateway/sds_gateway/templates/users/partials/dataset_share_modal.html
gateway/sds_gateway/templates/users/partials/download_confirmation.html
gateway/sds_gateway/templates/users/partials/share_modal.html
gateway/sds_gateway/users/mixins.py
gateway/sds_gateway/users/views.py

[SFDS-223](https://crc-dev.atlassian.net/browse/SFDS-223)
- Add a modal to add, display, and remove shared users
- Dynamic modal displays for sharing vs viewing/removing
- TODO: mirror for captures

Dataset Share Feature: Frontend

---

gateway/sds_gateway/static/css/components.css
gateway/sds_gateway/static/css/spectrumx_theme.css
gateway/sds_gateway/static/css/user_api_key_table.css

[https://crc-dev.atlassian.net/browse/SFDS-263](url)
Removed !important from css

remove important from css

---

gateway/sds_gateway/api_methods/serializers/capture_serializers.py
gateway/sds_gateway/api_methods/tests/test_capture_endpoints.py
gateway/sds_gateway/api_methods/views/capture_endpoints.py

Fixed path issue when checking for duplicate capture constraint. Added debug logging.

Fix duplicate capture

---

gateway/.gitignore
gateway/docs/dev-notes.md
gateway/makefile
gateway/scripts/.env.sh.example
gateway/scripts/create-snapshot.sh
gateway/scripts/restore-snapshot.sh

+ New `make snapshot`
+ Dev documentation for backup creation and restoration.

New target for creating psql backups
